# Generated by Django 4.2.30 on 2026-09-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_movie_unique_together_movie_backdrop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='original_language',
            field=models.CharField(blank=True, default='en', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_average',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='movie',
            name='vote_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
