# Generated by Django 5.2 on 2025-12-16 02:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='description',
            new_name='overview',
        ),
        migrations.AddField(
            model_name='movie',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movies', to='movies.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'release_year')},
        ),
    ]
